2024-11-22 16:59:28,854 - speechbrain.core - INFO - Beginning experiment!
2024-11-22 16:59:28,855 - speechbrain.core - INFO - Experiment folder: ~/lorgu.accent-recog-slt2022/CommonAccent/results/W2V2/AT/wav2vec2-large-xlsr-53/7001
2024-11-22 16:59:29,032 - speechbrain.utils.superpowers - DEBUG - asttokens==2.4.1
audioread==3.0.1
certifi==2024.8.30
cffi==1.17.1
cfgv==3.4.0
charset-normalizer==3.4.0
decorator==5.1.1
distlib==0.3.9
exceptiongroup==1.2.2
executing==2.1.0
filelock==3.16.1
fsspec==2024.10.0
huggingface-hub==0.26.2
HyperPyYAML==0.0.1
identify==2.6.2
idna==3.10
ipdb==0.13.9
ipython==8.29.0
jedi==0.19.2
joblib==0.14.1
librosa==0.9.2
llvmlite==0.43.0
matplotlib-inline==0.1.7
nodeenv==1.9.1
numba==0.60.0
numpy==1.24.4
packaging==24.2
pandas==1.5.3
parso==0.8.4
pexpect==4.9.0
pigz==2.9rc3
platformdirs==4.3.6
pooch==1.8.2
pre-commit==2.3.0
prompt_toolkit==3.0.48
ptyprocess==0.7.0
pure_eval==0.2.3
pycparser==2.22
Pygments==2.18.0
python-dateutil==2.9.0.post0
pytz==2024.2
PyYAML==6.0.2
regex==2024.11.6
requests==2.32.3
resampy==0.4.3
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.12
scikit-learn==1.0.2
scipy==1.8.1
sentencepiece==0.2.0
six==1.16.0
soundfile==0.12.1
speechbrain==0.5.13
stack-data==0.6.3
threadpoolctl==3.5.0
tokenizers==0.13.3
toml==0.10.2
torch==1.11.0
torchaudio==0.11.0
tqdm==4.67.0
traitlets==5.14.3
transformers==4.25.1
typing_extensions==4.12.2
urllib3==2.2.3
virtualenv==20.27.1
wcwidth==0.2.13


2024-11-22 16:59:29,034 - speechbrain.utils.superpowers - DEBUG - c886aa7


2024-11-22 16:59:29,208 - speechbrain.core - ERROR - Exception:
Traceback (most recent call last):
  File "/home/mipuc/lorgu.accent-recog-slt2022/CommonAccent/accent_id/train_w2v2.py", line 579, in <module>
    ) = dataio_prep(hparams)
  File "/home/mipuc/lorgu.accent-recog-slt2022/CommonAccent/accent_id/train_w2v2.py", line 381, in dataio_prep
    train_data = sb.dataio.dataset.DynamicItemDataset.from_csv(
  File "/home/mipuc/accentrecog3.10/lib/python3.10/site-packages/speechbrain/dataio/dataset.py", line 365, in from_csv
    data = load_data_csv(csv_path, replacements)
  File "/home/mipuc/accentrecog3.10/lib/python3.10/site-packages/speechbrain/dataio/dataio.py", line 127, in load_data_csv
    with open(csv_path, newline="") as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '~/lorgu.accent-recog-slt2022/CommonAccent/data/at_augmented_dev_regions/train.csv'
